question_data = [
    {"text": "1. In Python, a generator function is a type of iterator.", "answer": "True"},
    {"text": "2. Python supports multiple inheritance through classes.", "answer": "True"},
    {"text": "3. Decorators in Python can only be applied to functions.", "answer": "False"},
    {"text": "4. Python's Global Interpreter Lock (GIL) ensures that only one thread executes Python code at a time.", "answer": "True"},
    {"text": "5. In Python, a metaclass is an instance of a class.", "answer": "False"},
    {"text": "6. A list comprehension in Python is always faster than an equivalent for loop.", "answer": "False"},
    {"text": "7. Python's 'pass' statement does nothing and is ignored by the interpreter.", "answer": "True"},
    {"text": "8. In Python, the 'is' operator is used to compare the values of two objects.", "answer": "False"},
    {"text": "9. The 'zip' function in Python combines two or more iterables into a single iterable of tuples.", "answer": "True"},
    {"text": "10. Python allows you to create user-defined private methods and variables by prefixing them with a double underscore (__).", "answer": "True"},
    {"text": "11. Python's 'yield' statement is used to define a generator function.", "answer": "True"},
    {"text": "12. The 'asyncio' module in Python is used for asynchronous programming and concurrent execution.", "answer": "True"},
    {"text": "13. Python supports tail call optimization (TCO) for recursive functions.", "answer": "False"},
    {"text": "14. You can use 'assert' statements in production code to catch and handle exceptions.", "answer": "False"},
    {"text": "15. Python's 'with' statement is used for exception handling.", "answer": "False"},
    {"text": "16. Python's 'super' function can be used to call a method in a sibling class.", "answer": "True"},
    {"text": "17. Python has built-in support for regular expressions using the 're' module.", "answer": "True"},
    {"text": "18. Python's 'del' statement can be used to delete variables, objects, or items from a list.", "answer": "True"},
    {"text": "19. A Python set is an ordered collection of elements.", "answer": "False"},
    {"text": "20. The 'collections' module in Python provides specialized container datatypes.", "answer": "True"},
]
